#!/bin/bash
# A simple script to startup VPN Startup script for TryHackMe and HackTheBox
# Author: Brent Garren
# Date: November 23, 2023


while true; do
    OPTIONS=("Hack The Box" "TryHackMe" "Shutdown all VPN" Exit)

    select opt in "${OPTIONS[@]}"; do
        case $opt in
            "Hack The Box")
                clear_lines() {
                    local lines=$1
                    tput cuu $lines    # Move cursor up by $lines
                    tput ed            # Clear to end of screen
                }
                clear_lines 5
                HTB_OPTIONS=(Labs Competitive Academy "Go Back")
                select htb_opt in "${HTB_OPTIONS[@]}"; do
                    case $htb_opt in
                        "Labs")
                            sudo openvpn $HOME/OpenVPN/OPENVPNFILE.ovpn
                            break ;;
                        "Competitive")
                            sudo openvpn $HOME/OpenVPN/OPENVPNFILE.ovpn
                            break ;;
                        "Academy")
                            sudo openvpn $HOME/OpenVPN/OPENVPNFILE.ovpn
                            break ;;
                        "Go Back")
                            clear_lines() {
                                local lines=$1
                                tput cuu $lines    # Move cursor up by $lines
                                tput ed            # Clear to end of screen
                            }
                            clear_lines 5
                            break ;;
                        *)
                            echo "Invalid"
                            ;;
                    esac
                done
                break ;;

            "TryHackMe")
                sudo openvpn $HOME/OpenVPN/OPENVPNFILE.ovpn
                break ;;

            "Shutdown all VPN")
                sudo killall openvpn
                break ;;

            "Exit")
                exit
                break ;;
            *)
                echo "Invalid"
                ;;
        esac
    done
done
